# Generated by Django 4.1.2 on 2022-10-26 14:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usergroup_created_at_alter_usergroup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='demo id')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('title', models.CharField(max_length=240, unique=True, verbose_name='title')),
                ('short_desc', models.CharField(max_length=240, verbose_name='short desc')),
                ('detail_desc', models.CharField(max_length=240, verbose_name='detail desc')),
                ('file', models.FileField(upload_to='demo files', validators=[django.core.validators.FileExtensionValidator(['py'])])),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='type id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(max_length=240, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='instance id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('host', models.CharField(blank=True, default='', max_length=240, verbose_name='host')),
                ('pid', models.IntegerField(blank=True, default=0, verbose_name='pid')),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demo')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='feedback id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('details', models.CharField(max_length=240, verbose_name='details')),
                ('generated_details', models.CharField(blank=True, default='', max_length=1500, verbose_name='generated details')),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feedbacktype')),
            ],
        ),
    ]
