# Generated by Django 4.1 on 2022-08-24 18:27

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User(name="Hans User", password="mysecretpassword", is_admin=True).save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_demo_feedback_feedbacktype_host_instance_user_and_more'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
