# Generated by Django 4.1.2 on 2022-10-29 16:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_feedback_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='user_groups',
            field=models.ManyToManyField(related_name='authorized_user_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demo',
            name='file',
            field=models.FileField(upload_to='demo_files', validators=[django.core.validators.FileExtensionValidator(['py'])]),
        ),
    ]
