# Generated by Django 4.1.2 on 2022-10-29 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_demo_user_groups_alter_demo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='authorized_user_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
