# Generated by Django 4.1.2 on 2022-10-30 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_demo_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='accessible_demos', to=settings.AUTH_USER_MODEL),
        ),
    ]
