# Generated by Django 4.1.1 on 2022-09-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_instance_unique_together_instance_pid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together={('host', 'pid')},
        ),
        migrations.RemoveField(
            model_name='instance',
            name='port',
        ),
    ]
