# Generated by Django 4.1.1 on 2022-09-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_instance_unique_together_remove_instance_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='user',
            new_name='user_id',
        ),
    ]
