# Generated by Django 4.1.2 on 2022-10-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_instance_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='host',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='pid'),
        ),
    ]
