# Generated by Django 4.1.2 on 2022-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_instance_host_alter_instance_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='host',
            field=models.CharField(max_length=240, null=True, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='pid',
            field=models.IntegerField(null=True, verbose_name='pid'),
        ),
    ]
