version: "3"

services:
  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: http://127.0.0.1, api
        DJANGO_SECRET_KEY: "supersecretkeyjustfortesting"
        DJANGO_CORS_ORIGIN_WHITELIST: http://127.0.0.1
    command: gunicorn mplweb.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: 192.168.2.116:8000
    volumes:
      - build_folder:/frontend/build
  nginx:
    image: nginx:latest
    command: sudo chown -R nginx:nginx *
    command: sudo chmod 755 /var/www/frontend
    command: sudo chmod 644 /var/www/frontend/*
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  build_folder:
