# Generated by Django 4.1 on 2022-08-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='demo_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('title', models.CharField(max_length=240, verbose_name='title')),
                ('short_desc', models.CharField(max_length=240, verbose_name='short_desc')),
                ('detail_desc', models.CharField(max_length=240, verbose_name='detail_desc')),
                ('file_path', models.FilePathField(verbose_name='file_path')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='feedback_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('details', models.CharField(max_length=240, verbose_name='name')),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demo')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='type_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('name', models.CharField(max_length=240, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='host_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('ip_address', models.GenericIPAddressField(verbose_name='host')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='instance_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('port', models.IntegerField(verbose_name='port')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.host')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('name', models.CharField(max_length=240, verbose_name='name')),
                ('password', models.CharField(max_length=240, verbose_name='password')),
                ('is_admin', models.BooleanField(verbose_name='is_admin')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='instance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feedbacktype'),
        ),
        migrations.AddField(
            model_name='demo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
