# Generated by Django 4.1 on 2022-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_webserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='title',
            field=models.CharField(max_length=240, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='feedbacktype',
            name='name',
            field=models.CharField(max_length=240, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=240, unique=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together={('host', 'port')},
        ),
    ]
