# Generated by Django 4.1 on 2022-09-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_demo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='created_by',
            new_name='user_id',
        ),
    ]
