# Generated by Django 4.1 on 2022-09-08 15:27

from django.db import migrations, models


def create_data(apps, schema_editor):
    Host = apps.get_model('api', 'Host')
    Host(ip_address="127.0.0.1").save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_created_by_demo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='ip_address'),
        ),
        migrations.RunPython(create_data),
    ]
