# Generated by Django 4.1 on 2022-09-08 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_host_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='demo',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.demo'),
            preserve_default=False,
        ),
    ]
