# Generated by Django 4.1 on 2022-09-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_instance_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demo'),
        ),
    ]
