# Generated by Django 4.1 on 2022-09-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_instance_demo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instance',
            name='pid',
            field=models.IntegerField(default=0, verbose_name='pid'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together={('host', 'port', 'pid')},
        ),
    ]
