# Generated by Django 4.1.2 on 2022-10-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_feedback_stacktrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='created_at'),
        ),
    ]
