# Generated by Django 4.1.2 on 2022-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_feedback_stacktrace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='host',
            field=models.CharField(blank=True, default='', max_length=240, unique=True, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='pid',
            field=models.IntegerField(blank=True, verbose_name='pid'),
        ),
    ]
