# Generated by Django 4.1.2 on 2022-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_instance_host_alter_instance_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='pid',
            field=models.IntegerField(blank=True, default=0, verbose_name='pid'),
        ),
    ]
