# Generated by Django 4.1.2 on 2022-10-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_instance_host_alter_instance_pid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set(),
        ),
    ]
