# Generated by Django 4.1.2 on 2022-10-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_instance_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Host',
        ),
    ]
