# Generated by Django 4.1 on 2022-08-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0005_alter_demo_title_alter_feedbacktype_name_and_more'),
    ]

    operations = [
    ]
