# Generated by Django 4.1 on 2022-08-25 15:22

from django.db import migrations

def create_data(apps, schema_editor):
    FeedbackType = apps.get_model('webserver', 'FeedbackType')
    FeedbackType(name="bugreport").save()
    FeedbackType(name="comment").save()

class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0007_alter_demo_file_path'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
