# Generated by Django 4.1 on 2022-08-31 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0008_add_feedback_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='file_path',
        ),
        migrations.AddField(
            model_name='demo',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='demo_files'),
            preserve_default=False,
        ),
    ]
