# Generated by Django 4.1 on 2022-08-31 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0009_remove_demo_file_path_demo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='file',
            field=models.FileField(upload_to='demo_files', validators=[django.core.validators.FileExtensionValidator(['py'])]),
        ),
    ]
